import type { WorkbookAuditReport } from '../types/audit';

/**
 * Formats bytes into a human-readable string.
 */
function formatBytes(bytes: number): string {
  if (bytes === 0) return '0 B';
  const k = 1024;
  const sizes = ['B', 'KB', 'MB', 'GB'];
  const i = Math.floor(Math.log(bytes) / Math.log(k));
  return parseFloat((bytes / Math.pow(k, i)).toFixed(1)) + ' ' + sizes[i];
}

/**
 * Generates a clean, professional Markdown audit report suitable for Slack, Notion, or GitHub.
 */
export function generateMarkdownReport(report: WorkbookAuditReport): string {
  const dateStr = new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'short',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  });

  const lines: string[] = [];

  lines.push(`# 🐕 SheetHound Audit Report: ${report.fileName}`);
  lines.push(`*Generated by SheetHound (by Utharam) on ${dateStr}*`);
  lines.push(`*Audited 100% in-browser with zero server uploads*\n`);

  lines.push(`---`);
  lines.push(`## 📊 Executive Summary`);
  lines.push(`- **Total Worksheets:** ${report.totalSheets} (${report.visibleSheetsCount} Visible, ${report.hiddenSheetsCount} Hidden, ${report.veryHiddenSheetsCount} Very Hidden)`);
  lines.push(`- **Total Formulas:** ${report.totalFormulas}`);
  lines.push(`- **Formula Errors Detected:** ${report.totalErrors}`);
  lines.push(`- **External Workbook References:** ${report.totalExternalLinks} across ${report.uniqueExternalFiles.length} file(s)`);
  lines.push(`- **Stray / Outlier Data Alerts:** ${report.strayDataWarningCount}`);
  lines.push(`- **Unique Fonts Used:** ${report.uniqueFontsCount}`);
  lines.push(`- **Unique Colors Used:** ${report.uniqueColorsCount}\n`);

  // External Links Section
  lines.push(`---`);
  lines.push(`## 🔗 External Links Registry (${report.totalExternalLinks})`);
  if (report.externalLinksRegistry.length === 0) {
    lines.push(`> ✅ **No external workbook links detected.** Safe to share externally without #REF! risks.\n`);
  } else {
    lines.push(`> ⚠️ **Warning:** The following cells reference external files. Opening this workbook on another machine will return \`#REF!\` unless broken/hardcoded.`);
    lines.push(`\n| Cell | Target Workbook | Target Range | Formula |`);
    lines.push(`| :--- | :--- | :--- | :--- |`);
    report.externalLinksRegistry.forEach((link) => {
      const loc = `${link.sheetName}!${link.cell}`;
      const target = `[${link.targetWorkbook}]`;
      const range = link.targetSheet ? `${link.targetSheet}!${link.targetRange || ''}` : '—';
      const formula = link.formula.startsWith('=') ? link.formula : `=${link.formula}`;
      lines.push(`| \`${loc}\` | **${target}** | \`${range}\` | \`${formula}\` |`);
    });
    lines.push(``);
  }

  // Formula Errors Section
  lines.push(`---`);
  lines.push(`## 💥 Formula Errors Registry (${report.totalErrors})`);
  if (report.errorsRegistry.length === 0) {
    lines.push(`> ✅ **Zero formula evaluation errors detected.** All calculated formulas evaluated cleanly.\n`);
  } else {
    lines.push(`\n| Cell | Error Type | Formula | Value |`);
    lines.push(`| :--- | :--- | :--- | :--- |`);
    report.errorsRegistry.forEach((err) => {
      const loc = `${err.sheetName}!${err.cell}`;
      const formula = err.formula ? (err.formula.startsWith('=') ? err.formula : `=${err.formula}`) : '—';
      lines.push(`| \`${loc}\` | **${err.errorType}** | \`${formula}\` | \`${err.cachedValue || err.errorType}\` |`);
    });
    lines.push(``);
  }

  // Worksheets & Stray Data Section
  lines.push(`---`);
  lines.push(`## 📑 Worksheets & Spatial Density Breakdown`);
  lines.push(`\n| Sheet Name | State | Boundary | Farthest Cell | Spatial Cluster / Stray Status | Errors |`);
  lines.push(`| :--- | :--- | :--- | :--- | :--- | :--- |`);
  report.sheets.forEach((s) => {
    const clusterStr = s.heatmap ? `${s.heatmap.mainClusterBounds.colStartLetter}${s.heatmap.mainClusterBounds.rowStart}..${s.heatmap.mainClusterBounds.colEndLetter}${s.heatmap.mainClusterBounds.rowEnd} (${s.heatmap.mainClusterBounds.percentageOfData}%)` : '—';
    const strayStr = s.boundary.hasStrayCells ? `⚠️ **STRAY OUTLIER** (${s.boundary.farthestCell})` : `✓ Clustered (${clusterStr})`;
    lines.push(`| **${s.name}** | \`${s.visibility}\` | \`Row 1..${s.boundary.maxRow}, Col 1..${s.boundary.maxCol}\` | \`${s.boundary.farthestCell}\` | ${strayStr} | ${s.errorCount} |`);
  });
  lines.push(``);

  // Design Section
  lines.push(`---`);
  lines.push(`## 🎨 Typography & Brand Colors`);
  lines.push(`- **Fonts:** ${report.fontInventory.map((f) => `\`${f.name}\` (${f.count} cells)`).join(', ')}`);
  lines.push(`- **Color Palette (Top 6):** ${report.colorPalette.slice(0, 6).map((c) => `\`${c.hex}\` (${c.count} cells)`).join(', ')}\n`);

  lines.push(`---`);
  lines.push(`*Audited by SheetHound • by Utharam (https://utharam.github.io/) • Dedicated to Veeran the Indian Spitz 🐾*`);

  return lines.join('\n');
}

/**
 * Generates an executive-grade, standalone printable HTML document.
 * Perfectly styled for printing to PDF or paper without website chrome.
 */
export function generatePrintableHtml(report: WorkbookAuditReport): string {
  const dateStr = new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'short',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  });

  const hasIssues =
    report.totalErrors > 0 ||
    report.totalExternalLinks > 0 ||
    report.veryHiddenSheetsCount > 0 ||
    report.strayDataWarningCount > 0;

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>SheetHound Audit Certificate - ${report.fileName}</title>
  <style>
    @page {
      margin: 12mm 15mm;
      size: A4 portrait;
    }
    *, *:before, *:after {
      box-sizing: border-box;
      -webkit-print-color-adjust: exact !important;
      print-color-adjust: exact !important;
      color-adjust: exact !important;
    }
    body {
      margin: 0;
      padding: 24px;
      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif;
      color: #0f172a;
      background: #ffffff;
      line-height: 1.45;
      font-size: 10pt;
    }
    .print-controls {
      display: flex;
      align-items: center;
      justify-content: space-between;
      background: #f8fafc;
      border: 1px solid #e2e8f0;
      padding: 10px 16px;
      border-radius: 8px;
      margin-bottom: 20px;
    }
    .print-btn {
      background: #0f172a;
      color: #ffffff;
      border: none;
      padding: 8px 16px;
      font-weight: 600;
      border-radius: 6px;
      cursor: pointer;
      font-size: 12px;
      display: inline-flex;
      align-items: center;
      gap: 6px;
    }
    .print-btn:hover {
      background: #334155;
    }
    .header {
      display: flex;
      align-items: flex-start;
      justify-content: space-between;
      border-bottom: 2px solid #0f172a;
      padding-bottom: 12px;
      margin-bottom: 16px;
    }
    .brand {
      display: flex;
      align-items: center;
      gap: 10px;
    }
    .brand-icon {
      font-size: 28px;
    }
    .brand-title {
      font-size: 18pt;
      font-weight: 900;
      letter-spacing: -0.5px;
      color: #0f172a;
      margin: 0;
      line-height: 1.1;
    }
    .brand-sub {
      font-size: 8.5pt;
      color: #64748b;
      margin-top: 2px;
      font-weight: 500;
    }
    .meta-box {
      text-align: right;
      font-size: 8pt;
      color: #64748b;
    }
    .doc-title {
      font-size: 12pt;
      font-weight: 800;
      color: #0f172a;
      text-transform: uppercase;
      letter-spacing: 0.5px;
      margin: 0 0 4px 0;
    }
    .verdict-banner {
      padding: 10px 14px;
      border-radius: 6px;
      margin-bottom: 16px;
      display: flex;
      align-items: center;
      justify-content: space-between;
      border: 1px solid ${hasIssues ? '#fde68a' : '#a7f3d0'};
      background: ${hasIssues ? '#fefce8' : '#ecfdf5'};
      color: ${hasIssues ? '#854d0e' : '#065f46'};
    }
    .verdict-text {
      font-weight: 700;
      font-size: 10.5pt;
    }
    .verdict-desc {
      font-size: 8.5pt;
      margin-top: 2px;
      color: #475569;
    }
    .scorecard-grid {
      display: grid;
      grid-template-columns: repeat(4, 1fr);
      gap: 10px;
      margin-bottom: 18px;
    }
    .score-card {
      border: 1px solid #e2e8f0;
      border-radius: 6px;
      padding: 8px 12px;
      background: #fafafa;
    }
    .score-label {
      font-size: 7.5pt;
      font-weight: 700;
      color: #64748b;
      text-transform: uppercase;
      letter-spacing: 0.5px;
    }
    .score-value {
      font-size: 16pt;
      font-weight: 900;
      color: #0f172a;
      margin: 3px 0 2px 0;
    }
    .score-sub {
      font-size: 7.5pt;
      color: #64748b;
    }
    h3 {
      font-size: 10.5pt;
      font-weight: 800;
      margin: 18px 0 8px 0;
      color: #0f172a;
      border-bottom: 1.5px solid #0f172a;
      padding-bottom: 4px;
      text-transform: uppercase;
      letter-spacing: 0.4px;
      break-after: avoid;
      page-break-after: avoid;
    }
    .header, .verdict-banner, .scorecard-grid {
      break-inside: avoid;
      page-break-inside: avoid;
    }
    table {
      width: 100%;
      border-collapse: collapse;
      margin-bottom: 14px;
      font-size: 8.5pt;
      page-break-inside: auto;
    }
    tr {
      page-break-inside: avoid;
      page-break-after: auto;
    }
    th, td {
      border: 1px solid #cbd5e1;
      padding: 5px 8px;
      text-align: left;
    }
    th {
      background: #f1f5f9;
      font-weight: 700;
      color: #334155;
      text-transform: uppercase;
      font-size: 7.5pt;
      letter-spacing: 0.3px;
    }
    td.mono, th.mono {
      font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace;
    }
    .badge {
      display: inline-block;
      padding: 1px 6px;
      border-radius: 3px;
      font-size: 7.5pt;
      font-weight: 700;
      text-transform: uppercase;
    }
    .badge-danger { background: #fee2e2; color: #991b1b; }
    .badge-warning { background: #fef3c7; color: #92400e; }
    .badge-success { background: #dcfce7; color: #166534; }
    .badge-neutral { background: #f1f5f9; color: #475569; }
    .footer {
      margin-top: 24px;
      border-top: 1px solid #e2e8f0;
      padding-top: 10px;
      display: flex;
      align-items: center;
      justify-content: space-between;
      font-size: 7.5pt;
      color: #94a3b8;
    }
    @media print {
      body { padding: 0; }
      .print-controls { display: none !important; }
      @page { margin: 10mm 12mm; }
    }
  </style>
</head>
<body>

  <!-- Screen-only controls -->
  <div class="print-controls">
    <div>
      <strong style="font-size: 13px;">🐕 SheetHound Audit Certificate</strong>
      <span style="color: #64748b; font-size: 12px; margin-left: 8px;">Ready to print or save as PDF</span>
    </div>
    <div style="display: flex; gap: 8px;">
      <button onclick="window.print()" class="print-btn">🖨️ Print / Save as PDF</button>
      <button onclick="window.close()" style="background:#e2e8f0; border:none; padding:8px 14px; border-radius:6px; font-size:12px; cursor:pointer; font-weight:600;">Close</button>
    </div>
  </div>

  <!-- Certificate Header -->
  <div class="header">
    <div class="brand">
      <span class="brand-icon">🐕</span>
      <div>
        <h1 class="brand-title">SheetHound</h1>
        <div class="brand-sub">The Spreadsheet Watchdog • by Utharam</div>
      </div>
    </div>
    <div class="meta-box">
      <div class="doc-title">Pre-Flight Audit Certificate</div>
      <div><strong>File:</strong> ${report.fileName} (${formatBytes(report.fileSizeBytes)})</div>
      <div><strong>Audited:</strong> ${dateStr}</div>
      <div style="color: #16a34a; font-weight: 600;">🔒 100% In-Browser Memory (Zero Uploads)</div>
    </div>
  </div>

  <!-- Verdict Banner -->
  <div class="verdict-banner">
    <div>
      <div class="verdict-text">
        ${hasIssues ? '⚠️ Pre-Flight Notice: Potential Issues Detected' : '✅ Clean Bill of Health: Veeran Approves This Workbook'}
      </div>
      <div class="verdict-desc">
        ${hasIssues 
          ? `SheetHound identified ${report.totalErrors} formula errors, ${report.totalExternalLinks} external file dependencies, and ${report.strayDataWarningCount} isolated stray cell islands. Review details below.`
          : 'All evaluated formulas are clean, zero broken links were found, and data bounds are compact.'}
      </div>
    </div>
    <span class="badge ${hasIssues ? 'badge-warning' : 'badge-success'}">
      ${hasIssues ? 'Action Advised' : 'Safe to Send'}
    </span>
  </div>

  <!-- Scorecard -->
  <div class="scorecard-grid">
    <div class="score-card">
      <div class="score-label">Worksheets</div>
      <div class="score-value">${report.totalSheets}</div>
      <div class="score-sub">${report.visibleSheetsCount} Visible • ${report.hiddenSheetsCount} Hidden • ${report.veryHiddenSheetsCount} VeryHidden</div>
    </div>
    <div class="score-card">
      <div class="score-label">Formula Errors</div>
      <div class="score-value" style="color: ${report.totalErrors > 0 ? '#b91c1c' : '#0f172a'};">${report.totalErrors}</div>
      <div class="score-sub">${report.totalErrors > 0 ? 'Contains #REF! or #DIV/0!' : 'All formulas valid'}</div>
    </div>
    <div class="score-card">
      <div class="score-label">External Dependencies</div>
      <div class="score-value" style="color: ${report.totalExternalLinks > 0 ? '#b45309' : '#0f172a'};">${report.totalExternalLinks}</div>
      <div class="score-sub">${report.totalExternalLinks > 0 ? `${report.uniqueExternalFiles.length} file(s) referenced` : 'Zero external links'}</div>
    </div>
    <div class="score-card">
      <div class="score-label">Stray Data Outliers</div>
      <div class="score-value" style="color: ${report.strayDataWarningCount > 0 ? '#7e22ce' : '#0f172a'};">${report.strayDataWarningCount}</div>
      <div class="score-sub">${report.strayDataWarningCount > 0 ? 'Isolated scratchpads found' : 'Compact bounds'}</div>
    </div>
  </div>

  <!-- External Links Table -->
  <h3>🔗 External Links Registry (${report.totalExternalLinks})</h3>
  ${report.externalLinksRegistry.length === 0 
    ? '<p style="font-size: 8.5pt; color: #166534; background: #dcfce7; padding: 6px 10px; border-radius: 4px;">✅ No external links detected. Safe to share externally without #REF! risks.</p>'
    : `<table>
        <thead>
          <tr>
            <th style="width: 22%;">Cell Location</th>
            <th style="width: 28%;">Target Workbook</th>
            <th style="width: 18%;">Target Sheet / Range</th>
            <th style="width: 32%;">Formula Expression</th>
          </tr>
        </thead>
        <tbody>
          ${report.externalLinksRegistry.map(link => `
            <tr>
              <td class="mono"><strong>${link.sheetName}!${link.cell}</strong></td>
              <td><strong>[${link.targetWorkbook}]</strong></td>
              <td class="mono">${link.targetSheet ? `${link.targetSheet}!${link.targetRange || ''}` : '—'}</td>
              <td class="mono" style="word-break: break-all;">${link.formula.startsWith('=') ? link.formula : `=${link.formula}`}</td>
            </tr>
          `).join('')}
        </tbody>
      </table>`
  }

  <!-- Formula Errors Table -->
  <h3>💥 Formula Errors &amp; Broken References (${report.totalErrors})</h3>
  ${report.errorsRegistry.length === 0
    ? '<p style="font-size: 8.5pt; color: #166534; background: #dcfce7; padding: 6px 10px; border-radius: 4px;">✅ Zero formula evaluation errors detected. All evaluated formulas computed cleanly.</p>'
    : `<table>
        <thead>
          <tr>
            <th style="width: 22%;">Cell Address</th>
            <th style="width: 16%;">Error Type</th>
            <th style="width: 42%;">Formula</th>
            <th style="width: 20%;">Cached Value</th>
          </tr>
        </thead>
        <tbody>
          ${report.errorsRegistry.map(err => `
            <tr>
              <td class="mono"><strong>${err.sheetName}!${err.cell}</strong></td>
              <td><span class="badge badge-danger">${err.errorType}</span></td>
              <td class="mono" style="word-break: break-all;">${err.formula ? (err.formula.startsWith('=') ? err.formula : `=${err.formula}`) : 'Direct Error Value'}</td>
              <td class="mono" style="color: #b91c1c; font-weight: bold;">${err.cachedValue || err.errorType}</td>
            </tr>
          `).join('')}
        </tbody>
      </table>`
  }

  <!-- Worksheets & Stray Data Table -->
  <h3>📑 Worksheets &amp; Boundary Analysis (${report.totalSheets})</h3>
  <table>
    <thead>
      <tr>
        <th>Worksheet</th>
        <th>Visibility</th>
        <th>Data Bounds</th>
        <th>Farthest Cell</th>
        <th>Stray Data Alert / Status</th>
        <th>Formulas</th>
      </tr>
    </thead>
    <tbody>
      ${report.sheets.map(s => `
        <tr>
          <td><strong>${s.name}</strong></td>
          <td>
            <span class="badge ${s.visibility === 'veryHidden' ? 'badge-danger' : s.visibility === 'hidden' ? 'badge-warning' : 'badge-success'}">
              ${s.visibility}
            </span>
          </td>
          <td class="mono">R1..R${s.boundary.maxRow}, C1..C${s.boundary.maxCol}</td>
          <td class="mono"><strong>${s.boundary.farthestCell}</strong></td>
          <td>
            ${s.boundary.hasStrayCells 
              ? `<span class="badge badge-warning">Stray Alert: ${s.boundary.farthestCell}</span> <span style="font-size: 7.5pt; color: #64748b;">(Cluster: ${s.heatmap?.mainClusterBounds.colStartLetter || ''}${s.heatmap?.mainClusterBounds.rowStart || 1}..${s.heatmap?.mainClusterBounds.colEndLetter || ''}${s.heatmap?.mainClusterBounds.rowEnd || 1})</span>` 
              : `<span style="color: #166534; font-size: 7.5pt;">✓ Clustered in ${s.heatmap?.mainClusterBounds.colStartLetter || ''}${s.heatmap?.mainClusterBounds.rowStart || 1}..${s.heatmap?.mainClusterBounds.colEndLetter || ''}${s.heatmap?.mainClusterBounds.rowEnd || 1} (${s.heatmap?.mainClusterBounds.percentageOfData || 100}%)</span>`}
          </td>
          <td>${s.formulaCount}</td>
        </tr>
      `).join('')}
    </tbody>
  </table>

  <!-- Typography & Styling Footprint -->
  <h3>🎨 Typography &amp; Brand Styling</h3>
  <div style="font-size: 8.5pt; color: #475569; margin-bottom: 16px;">
    <div><strong>Detected Fonts (${report.uniqueFontsCount}):</strong> ${report.fontInventory.map(f => `${f.name} (${f.count} cells)`).join(', ')}</div>
    <div style="margin-top: 4px;"><strong>Color Swatches (${report.uniqueColorsCount}):</strong> ${report.colorPalette.slice(0, 8).map(c => `<span class="mono">${c.hex}</span>`).join(', ')}</div>
  </div>

  <!-- Document Footer -->
  <div class="footer">
    <div>
      Audited by <strong>SheetHound</strong> • by <a href="https://utharam.github.io/" style="color:#0f172a; text-decoration:none;"><strong>Utharam</strong></a> • Dedicated to Veeran the Indian Spitz 🐾
    </div>
    <div>
      🔒 Client-Side In-Browser Audit • Confidentiality Guaranteed
    </div>
  </div>

  <script>
    function launchPrint() {
      setTimeout(function() {
        window.print();
      }, 300);
    }
    if (document.readyState === 'complete') {
      launchPrint();
    } else {
      window.addEventListener('load', launchPrint);
    }
  </script>
</body>
</html>`;
}

/**
 * Triggers a browser file download for a generated string.
 */
export function triggerFileDownload(content: string, fileName: string, mimeType: string) {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = fileName;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

/**
 * Exports JSON audit data.
 */
export function exportJsonReport(report: WorkbookAuditReport) {
  const jsonStr = JSON.stringify(report, null, 2);
  const cleanName = report.fileName.replace(/\.[^/.]+$/, '');
  triggerFileDownload(jsonStr, `${cleanName}-SheetHound-Audit.json`, 'application/json');
}

/**
 * Exports Markdown audit report.
 */
export function exportMarkdownReport(report: WorkbookAuditReport) {
  const mdStr = generateMarkdownReport(report);
  const cleanName = report.fileName.replace(/\.[^/.]+$/, '');
  triggerFileDownload(mdStr, `${cleanName}-SheetHound-Audit.md`, 'text/markdown');
}

/**
 * Exports standalone HTML audit report.
 */
export function exportHtmlReport(report: WorkbookAuditReport) {
  const htmlStr = generatePrintableHtml(report);
  const cleanName = report.fileName.replace(/\.[^/.]+$/, '');
  triggerFileDownload(htmlStr, `${cleanName}-SheetHound-Audit.html`, 'text/html');
}

/**
 * Triggers a dedicated, clean, audit-grade Print dialog.
 * Opens an isolated clean document tailored specifically for PDF/paper print.
 */
export function triggerPrintReport(report: WorkbookAuditReport) {
  const printWindow = window.open('', '_blank');
  if (!printWindow) {
    alert('Pop-up blocked! Please allow pop-ups for this site to print or save the PDF report, or use the "Download HTML / Markdown" option.');
    return;
  }
  printWindow.document.open();
  printWindow.document.write(generatePrintableHtml(report));
  printWindow.document.close();
}
